config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'tech-news', to: "pages#tech_news"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#index'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  # Custom Scope then it can be called from the controller to separate the logic from the controller
  scope :ruby_on_rails, -> {where(subtitle: 'Ruby on Rails')} #LAMBDA
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :portfolio_find, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.all.by_position
  end

  def sort
    params[:order].each do |k,v|
      Portfolio.find(v[:id]).update(position: v[:position])
    end

    render nothing: true
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    if @portfolio_item.save
      redirect_to @portfolio_item
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @portfolio_item.update(portfolio_params)
      redirect_to portfolio_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    redirect_to portfolios_path
  end

  private
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :destroy])
    end

    def portfolio_find
      @portfolio_item = Portfolio.find(params[:id])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    # byebug
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    else
      image_generator(height: '350', width: '200')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle, class: "form-control" %>
    </div>
    <div class="form-group">
      <label class="btn btn-secondary">
        Upload a thumb image <%= f.file_field :main_image, style: "display:none;" %>
      </label>
    </div>
    <div class="form-group">
      <label class="btn btn-secondary">
        Upload a main image <%= f.file_field :thumb_image, style: "display:none;" %>
      </label>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control", rows: 12 %>
    </div>
  </div>
</div>

<div class="col-md-12">
  <h2>Technologies Used</h2>
  <div>
    <%= f.fields_for :technologies do |technology_form| %>
    <%= render 'technology_fields', f: technology_form %>
    <% end %>
  </div>
  <div>
    <%= link_to_add_association 'Add Technology', f, :technologies %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit portfolio item", class: "btn btn-primary btn-block"  %>
  </div>
  <% end %>
</div>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_img(portfolio_item.main_image, 'thumb') %>
  <h2 class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></span>
  </h2>
  <h3><span><%= portfolio_item.subtitle %></h3></span>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Delete Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit a portfolio item</h1>
  <%= render 'form' %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin)%>">
      <%#= link_to "NEW", new_portfolio_path if logged_in?(:site_admin) %>

      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container">
  <h1>Create a new portfolio item</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.thumb_image, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <%#= @portfolio_item.inspect %>
      <em><%= @portfolio_item.title %></em>
      <p><%= @portfolio_item.body %></p>
      <h2>Technologies used</h2>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name%></p>
      <% end %>

      <%= link_to "BACK", portfolios_path %>
      <% if logged_in?(:site_admin) %>
         | <%= link_to "EDIT", edit_portfolio_path(@portfolio_item[:id]) if logged_in?(:site_admin) %> |
        <%= link_to "DELETE", portfolio_path(@portfolio_item), method: :delete, data: { confirm: "Are you sure mofo?"} if logged_in?(:site_admin) %>
      <% end %>
    </div>
  </div>
</div>