config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'tech-news', to: "pages#tech_news"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#index'

end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Pedro's Portfolio", sticky: false, time: 10000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Pedro's Portfolio", sticky: false, time: 10000) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Pedro's Portfolio", sticky: false, time: 1000) %>
<% end %>

app/views/shared/_application_navbar.html.erb
<header class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Pedro Monsalve", root_path %></h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper('nav-link', 'span') %>
      <%= login_logic_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= @copyright %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Blog</h1>
    <%= link_to 'Write a new blog', new_blog_path, class: 'btn btn-primary' if logged_in?(:site_admin)%>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav">
      <%= nav_helper('nav-link', 'span') %>
      <%= login_logic_helper('nav-link') %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-sm-3 ml-sm-auto blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Find Me</h4>
    <div class="social-links">
      <a href="#"><%= fa_icon "github 2x"%> </a>
      <a href="#"><%= fa_icon "twitter 2x"%> </a>
      <a href="#"><%= fa_icon "instagram 2x"%>
    </div>
  </div>
</aside>

app/views/shared/_footer.html.erb
<footer class="mastfoot">
  <div class="inner">
    <p class="appfooter"><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="<%= location %>"> <!-- location is a the parameter that will accept the argument from the partial call and location is just the variable name -->
  <%= nav_helper('text-white', 'span') %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
     <%= @copyright %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Porfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'About moi', about_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blogging', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Some of my work</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">

        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white', 'span') %>
          <li><strong><%= login_logic_helper('text-white') %></strong></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Pedro Monsalve</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>