config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'tech-news', to: "pages#tech_news"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#index'

end

app/views/layouts/_navbar.html.erb
<div class="<%= location %>"> <!-- location is a the parameter that will accept the argument from the partial call and location is just the variable name -->
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="<%= @seo_keywords %>" />


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%= render 'shared/application_navbar', location: 'top' %> <!-- location is the variable and top is the argument being passed into the partial -->
          <!-- <div id='background'></div> -->
          <%= video_tag(
              'HardDrivePhotojpeg.mp4',
              id: 'background',
              autoplay: true,
              loop: true,
              mute: true,
              poster: 'home_bg.png')

          %>
          <%= yield %>
          <br>
          <%= render 'shared/footer' %>
          <%= alerts %>
          <%= source_helper("application")%>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content="<%= @seo_keywords %>" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/blog_nav"%>
    <%= render "shared/blog_masthead"%>

    <main role="main" class="container">
      <div class="row">

        <%= yield %>

        <%= render "shared/blog_sidebar"%>
        <%= source_helper("blog")%>
      </div>

      <%= render "shared/blog_footer"%>

      <%= alerts %>
    </main>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="<%= @seo_keywords %>" />


    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/portfolio_nav'%>

    <%= render 'shared/portfolio_masthead' unless logged_in?(:site_admin)%>

    <%= yield %>

    <%= render 'shared/portfolio_footer'%>

    <%= source_helper("portfolio")%>

    <%= alerts %>
  </body>
</html>